import arcade

NUMBER_ROW = 17
NUMBER_COLUMN = 13
PIXEL_WIDTH = 30

SCREEN_WIDTH = NUMBER_COLUMN*PIXEL_WIDTH
SCREEN_HEIGHT = NUMBER_ROW*PIXEL_WIDTH
SCREEN_TITLE = "Caro by AIZero"
BACKGROUND_COLOR = arcade.csscolor.WHITE
LINE_COLOR = arcade.csscolor.RED
